### ISSUE TITLE
Perch Runway 3 support

### ISSUE THREAD

**Issue by mgkz** [PepperJack/Perch-member-tags#2]
Hello,

Thanks for the app, it's very handy to review all member tags.

The app seems to be functioning with Perch Runway 3, but there are a few visual glitches with the unstyled subnav, delete buttons, and row underline. It probably needs a few minor markup changes.

**Comment by duncrev** [comment]
Hi - yes I'm aware of that - there are some changes that have to be applied for it to work properly with Perch 3.  I've been very slack in not doing it, but I will get to it soon.  It's not too tricky to do.

Cheers.

**Comment by duncrev** [comment]
New version released.

**Comment by duncrev** [comment]
New version released.
